version: '2'

services:
  allinone:
    image: skanno22/ci_sample:latest
    container_name: ci_sample_allinone
    privileged: true
    volumes:
      - ../../ci_sample:/var/www/html/ci_sample
      - ./conf/httpd/httpd.conf:/etc/httpd/conf/httpd.conf
    ports:
      - 18080:80  #Apache httpd
      - 18443:443 #Apache httpd
    environment:
      - "TZ=Japan"
    command: /sbin/init
