version: '2'

services:
  allinone:
    image: skanno22/ci_sample:latest
    container_name: ci_sample_allinone
    privileged: true
    volumes:
      - ../:/var/www/html/ci_sample
      - ./conf/httpd/httpd.conf:/etc/httpd/conf/httpd.conf
    ports:
      - 18080:80  #Apache httpd
      - 18443:443 #Apache httpd
    environment:
      - "TZ=Japan"
    command: /sbin/init

  mysql1:
    image: mysql:5.7.17
    container_name: ci_sample_mysql1
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  mysql2:
    image: mysql:5.7.17
    container_name: ci_sample_mysql2
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  mysql3:
    image: mysql:5.7.17
    container_name: ci_sample_mysql3
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  mysql4:
    image: mysql:5.7.17
    container_name: ci_sample_mysql4
    ports:
      - "43306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

